# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsjpxJd6jQeZLaSBDMU1F8WDi0_ew4Ld
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from tensorflow.keras.models import load_model
import requests
import time

def load_binance_price():
    """
    Fetch latest BTC-USDT price data from Binance.
    Returns the most recent row as a DataFrame.
    """
    url = 'https://api.binance.com/api/v3/klines'
    params = {
        'symbol': 'BTCUSDT',
        'interval': '1m',
        'limit': 30
    }
    response = requests.get(url, params=params)
    if response.status_code != 200:
        return None

    data = response.json()
    df = pd.DataFrame(data, columns=[
        'timestamp', 'open', 'high', 'low', 'close', 'volume',
        'close_time', 'quote_asset_volume', 'number_of_trades',
        'taker_buy_base', 'taker_buy_quote', 'ignore'])

    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    df['close'] = df['close'].astype(float)
    df['high'] = df['high'].astype(float)
    df['low'] = df['low'].astype(float)
    df['volume'] = df['volume'].astype(float)
    df = df.sort_values('timestamp')
    return df

def compute_indicators(df):
    """ Compute the same technical indicators as used in training. """
    df['macd'] = df['close'].ewm(span=12).mean() - df['close'].ewm(span=26).mean()
    df['macd_diff'] = df['macd'] - df['macd'].ewm(span=9).mean()
    delta = df['close'].diff()
    gain = delta.where(delta > 0, 0.0)
    loss = -delta.where(delta < 0, 0.0)
    avg_gain = gain.rolling(14).mean()
    avg_loss = loss.rolling(14).mean()
    rs = avg_gain / avg_loss.replace(0, np.nan)
    df['rsi_14'] = 100 - (100 / (1 + rs))
    df['sma_10'] = df['close'].rolling(10).mean()
    std_20 = df['close'].rolling(20).std()
    sma_20 = df['close'].rolling(20).mean()
    bb_upper = sma_20 + 2 * std_20
    bb_lower = sma_20 - 2 * std_20
    df['bb_ratio'] = (df['close'] - bb_lower) / (bb_upper - bb_lower)
    df['atr'] = (df['high'] - df['low']).rolling(14).mean()
    df['obv'] = (np.sign(df['close'].diff()) * df['volume']).fillna(0).cumsum()
    df['log_volume'] = np.log1p(df['volume'])
    df['mean_volume_10'] = df['volume'].rolling(10).mean()
    df['volume_ratio'] = df['volume'] / df['mean_volume_10']
    df['rolling_std_5'] = df['close'].rolling(5).std()
    df['hour'] = df['timestamp'].dt.hour
    df['dayofweek'] = df['timestamp'].dt.dayofweek
    df.dropna(inplace=True)
    return df

def prepare_input(df, feature_cols):
    """Extract the last row with selected features."""
    return df[feature_cols].iloc[-1:].copy()

# --- Load models and scaler ---
with open("price_model_lgbm_5min.pkl", "rb") as f:
    model_lgbm = pickle.load(f)
with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)
model_brnn = load_model("price_model_brnn_5min.h5")


# --- Feature columns used during training ---
feature_cols = [
    'close', 'macd', 'macd_diff', 'rsi_14', 'sma_10', 'bb_ratio',
    'atr', 'obv', 'log_volume', 'mean_volume_10', 'volume_ratio',
    'rolling_std_5', 'hour', 'dayofweek'
]

st.set_page_config(layout="wide")
st.title("📈 Bitcoin 5-Minute Price Prediction App")
st.markdown("Upload your CSV file or fetch real-time market data to predict Bitcoin prices using LGBM and BRNN models.")

# --- Data input method ---
data_source = st.radio("Select Input Method:", ["Upload CSV", "Fetch Real-Time Market Data"])

if data_source == "Upload CSV":
    uploaded_file = st.file_uploader("Upload your CSV file:", type="csv")
    if uploaded_file:
        user_df = pd.read_csv(uploaded_file)
        st.write("Raw Uploaded Data:", user_df.head())
        try:
            X_input = user_df[feature_cols]
            X_scaled = scaler.transform(X_input)
            current_price = X_input['close'].values

            # LGBM prediction
            log_ret_lgbm = model_lgbm.predict(X_scaled)
            pred_price_lgbm = current_price * np.exp(log_ret_lgbm)

            # BRNN prediction
            seq_input = np.repeat(X_scaled[:, np.newaxis, :], 10, axis=1)
            log_ret_brnn = model_brnn.predict(seq_input).ravel()
            pred_price_brnn = current_price * np.exp(log_ret_brnn)

            result = pd.DataFrame({
                'Current Price': current_price,
                'LGBM Predicted Price': pred_price_lgbm,
                'BRNN Predicted Price': pred_price_brnn
            })
            st.write("📊 Prediction Result:", result)
        except Exception as e:
            st.error(f"Error in processing uploaded data: {e}")

elif data_source == "Fetch Real-Time Market Data":
    with st.spinner("Fetching real-time BTC price data from Binance..."):
        raw_df = load_binance_price()
        if raw_df is not None:
            df = compute_indicators(raw_df)
            X_input = prepare_input(df, feature_cols)
            X_scaled = scaler.transform(X_input)
            current_price = X_input['close'].values[0]

            # Predictions
            log_ret_lgbm = model_lgbm.predict(X_scaled)[0]
            pred_price_lgbm = current_price * np.exp(log_ret_lgbm)

            seq_input = np.repeat(X_scaled[np.newaxis, :, :], 10, axis=1)
            log_ret_brnn = model_brnn.predict(seq_input)[0, 0]
            pred_price_brnn = current_price * np.exp(log_ret_brnn)

            st.success("✅ Data fetched and processed.")
            st.write(f"**Current Price:** ${current_price:.2f}")
            st.write(f"**LGBM Prediction:** ${pred_price_lgbm:.2f}  ({log_ret_lgbm*100:.2f}% return)")
            st.write(f"**BRNN Prediction:** ${pred_price_brnn:.2f}  ({log_ret_brnn*100:.2f}% return)")
        else:
            st.error("Failed to fetch Binance data. Please try again later.")