# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3G7M5h8vqsGW1LnHCdNq9EhfXJ6D2Fo
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from tensorflow.keras.models import load_model
import requests
import time

def load_coingecko_price():
    """
    Fetch 1-minute BTC price data for the past hour from CoinGecko.
    Returns a DataFrame or None if failed.
    """
    url = "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart"
    params = {
        "vs_currency": "usd",
        "days": "1",
        "interval": "minute"
    }
    try:
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()
        prices = data.get("prices", [])  # [timestamp, price]
        if not prices:
            return None
        df = pd.DataFrame(prices, columns=["timestamp", "close"])
        df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")
        df = df.sort_values("timestamp")
        return df
    except Exception as e:
        print("Failed to fetch from CoinGecko:", e)
        return None

def compute_indicators(df):
    df['macd'] = df['close'].ewm(span=12).mean() - df['close'].ewm(span=26).mean()
    df['macd_diff'] = df['macd'] - df['macd'].ewm(span=9).mean()
    delta = df['close'].diff()
    gain = delta.where(delta > 0, 0.0)
    loss = -delta.where(delta < 0, 0.0)
    avg_gain = gain.rolling(14).mean()
    avg_loss = loss.rolling(14).mean()
    rs = avg_gain / avg_loss.replace(0, np.nan)
    df['rsi_14'] = 100 - (100 / (1 + rs))
    df['sma_10'] = df['close'].rolling(10).mean()
    std_20 = df['close'].rolling(20).std()
    sma_20 = df['close'].rolling(20).mean()
    bb_upper = sma_20 + 2 * std_20
    bb_lower = sma_20 - 2 * std_20
    df['bb_ratio'] = (df['close'] - bb_lower) / (bb_upper - bb_lower)
    df['rolling_std_5'] = df['close'].rolling(5).std()
    df['hour'] = df['timestamp'].dt.hour
    df['dayofweek'] = df['timestamp'].dt.dayofweek
    df.dropna(inplace=True)
    return df

def prepare_input(df, feature_cols):
    return df[feature_cols].iloc[-1:].copy()

with open("price_model_lgbm_5min.pkl", "rb") as f:
    model_lgbm = pickle.load(f)
with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)
model_brnn = load_model("price_model_brnn_5min.h5")

feature_cols = [
    'close', 'macd', 'macd_diff', 'rsi_14', 'sma_10', 'bb_ratio',
    'rolling_std_5', 'hour', 'dayofweek'
]

st.set_page_config(layout="wide")
st.title("📈 Bitcoin 5-Minute Price Prediction App")
st.markdown("Upload your CSV file or fetch real-time market data to predict Bitcoin prices using LGBM and BRNN models.")

data_source = st.radio("Select Input Method:", ["Upload CSV", "Fetch Real-Time Market Data"])

if data_source == "Upload CSV":
    uploaded_file = st.file_uploader("Upload your CSV file:", type="csv")
    if uploaded_file:
        user_df = pd.read_csv(uploaded_file)
        st.write("Raw Uploaded Data:", user_df.head())
        try:
            X_input = user_df[feature_cols]
            X_scaled = scaler.transform(X_input)
            current_price = X_input['close'].values
            log_ret_lgbm = model_lgbm.predict(X_scaled)
            pred_price_lgbm = current_price * np.exp(log_ret_lgbm)
            seq_input = np.repeat(X_scaled[:, np.newaxis, :], 10, axis=1)
            log_ret_brnn = model_brnn.predict(seq_input).ravel()
            pred_price_brnn = current_price * np.exp(log_ret_brnn)
            result = pd.DataFrame({
                'Current Price': current_price,
                'LGBM Predicted Price': pred_price_lgbm,
                'BRNN Predicted Price': pred_price_brnn
            })
            st.write("📊 Prediction Result:", result)
        except Exception as e:
            st.error(f"Error in processing uploaded data: {e}")

elif data_source == "Fetch Real-Time Market Data":
    with st.spinner("Fetching real-time BTC price data from CoinGecko..."):
        raw_df = load_coingecko_price()
        if raw_df is None:
            st.error("❌ Failed to fetch real-time data. Please upload CSV instead.")
            st.stop()
        df = compute_indicators(raw_df)
        X_input = prepare_input(df, feature_cols)
        X_scaled = scaler.transform(X_input)
        current_price = X_input['close'].values[0]
        log_ret_lgbm = model_lgbm.predict(X_scaled)[0]
        pred_price_lgbm = current_price * np.exp(log_ret_lgbm)
        seq_input = np.repeat(X_scaled[np.newaxis, :, :], 10, axis=1)
        log_ret_brnn = model_brnn.predict(seq_input)[0, 0]
        pred_price_brnn = current_price * np.exp(log_ret_brnn)
        st.success("✅ Data fetched and processed.")
        st.write(f"**Current Price:** ${current_price:.2f}")
        st.write(f"**LGBM Prediction:** ${pred_price_lgbm:.2f}  ({log_ret_lgbm*100:.2f}% return)")
        st.write(f"**BRNN Prediction:** ${pred_price_brnn:.2f}  ({log_ret_brnn*100:.2f}% return)")